version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - mongo
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/db

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db  

volumes:
  mongodb_data:
      driver: local

